### ISSUE TITLE
请教下这个返回是什么意思 ？是因为SOAPAction 为空么？

### ISSUE THREAD

**Issue by 704480904** [ximencx/ksoap2retrofit#1]
mheaderMap==={Content-Type=text/xml;charset=utf-8, SOAPAction=, User-Agent=ksoap2-android/2.6.0+, Accept-Encoding=gzip, Content-Length=412}
                                                                          requestData===<v:Envelope xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns:d="http://www.w3.org/2001/XMLSchema" xmlns:c="http://schemas.xmlsoap.org/soap/encoding/" xmlns:v="http://schemas.xmlsoap.org/soap/envelope/"><v:Header /><v:Body><n0:JobManageVII_UserCV_GetStat id="o0" c:root="1" xmlns:n0="http://tempuri.org/"><UserNeiMa i:type="d:string">3</UserNeiMa></n0:JobManageVII_UserCV_GetStat></v:Body></v:Envelope>
03-05 15:06:53.984 20321-20638/com.expert.newpams V/SoapRequestBodyConverter: RequestBody:<v:Envelope xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns:d="http://www.w3.org/2001/XMLSchema" xmlns:c="http://schemas.xmlsoap.org/soap/encoding/" xmlns:v="http://schemas.xmlsoap.org/soap/envelope/"><v:Header /><v:Body><n0:JobManageVII_UserCV_GetStat id="o0" c:root="1" xmlns:n0="http://tempuri.org/"><UserNeiMa i:type="d:string">3</UserNeiMa></n0:JobManageVII_UserCV_GetStat></v:Body></v:Envelope>

**Comment by ximencx** [comment]
是的
